<a href="https://colab.research.google.com/github/NIKKISAHA/machineLearning/blob/main/Upload_File_on_Colab_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# how to read a file on google colab, we cannot upload files on google colab , we have to upload it using zip or file compressed

import pandas as pd
path = pd.read_csv("features_30_sec.csv")
# "features_30_sec.csv" - replace this with file name and make sure that you have uploaded the file on google colab

#load from kares build in
from tensorflow.keras.datasets import imdb
(num_train_samples), (num_test_samples) = imdb.load_data(num_words=10000)

# another example
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# another example
from tensorflow.keras.preprocessing.image import ImageDataGenerator
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Extract the lfw-funneled.tgz file
!tar -xvf lfw-funneled.tgz
!file lfw-funneled.tgz
!ls -lh lfw-funneled.tgz

# Extract the zip file
!unzip -q /content/archive.zip -d /content/
!file archive.zip
!ls -lh archive.zip

In [ ]:
---- quesyion - I have downloaded the code in the path Path to dataset files: /root/.cache/kagglehub/datasets/jessicali9530/stanford-cars-dataset/versions/2
on google colab
Is it got downloaded on my system, where is it got downloaded ?

ans : No!
The files are not downloaded to your local system. They are stored in the Google Colab environment.

If you want to download the files to your system:

1. Go to the Google Colab file explorer.
2. Right-click on the file/folder.
3. Select "Download".

Or, use the `!download` command in a Colab cell. Here's an example:

You downloaded the Stanford Cars dataset to:

`/root/.cache/kagglehub/datasets/jessicali9530/stanford-cars-dataset/versions/2`

To download it to your local system:

1. Open a new cell in Google Colab.
2. Type: `!download /root/.cache/kagglehub/datasets/jessicali9530/stanford-cars-dataset/versions/2`
3. Press Shift+Enter.

The file will be downloaded to your local system!

In [ ]:
# ---------pre trained model---------

# Import necessary libraries
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.datasets import fashion_mnist

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
# base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(32, 32, 3))

# Freeze the early layers
for layer in base_model.layers:
    layer.trainable = False

# Add custom layers
x = base_model.output
x = Flatten()(x)
x = Dense(128, activation='relu')(x)
x = Dense(10, activation='sigmoid')(x)

# Create the new model
model = Model(inputs=base_model.input, outputs=x)

In [ ]:
# for opening the file directly, if you want to open it directly cuz you have already uploaded it and know the file name
from PIL import Image
img = Image.open('number_1.png')

#upload option will appear
from google.colab import files
imga = files.upload() #returns-dictionary,have to assain it to a veriable,in python whena function return value and you don't assain it you will get a warning
file_content = list(imga.keys())[0] #save the last uploaded file
img = file_content
print("file is ", img)

# then open it
# for opening the file
from PIL import Image
img = Image.open(img) #open the image


# For resixing
import numpy as np
img = img.resize((28, 28))
img = img.convert('L')  # Convert to grayscale
img = img.convert('RGB') # Convert to rgb
img = np.array(img) / 255.0  # Normalize pixel values
img = img.reshape((1, 28, 28, 1)) #Add a size
img = np.expand_dims(img,axis=0) #batch dimension to the image


# prediction
prediction = model.predict(img)
predicted_class = np.argmax(prediction)
print("Predicted digit class:", predicted_class)
class_labels = [ 'T-shirt/top','Trouser','Pullover', 'Dress','Coat','Sandal','Shirt','Sneaker','Bag','Ankle boot']
predicted_class_index = np.argmax(prediction)
predicted_class_label = class_labels[predicted_class_index]
print('Predicted class:', predicted_class_label)

--------- question - I have downloaded the code in the path Path to dataset files: /root/.cache/kagglehub/datasets/jessicali9530/stanford-cars-dataset/versions/2
Then I did --
Train_dir = os.path.join(path, 'cars_train')
test_dir = os.path.join(path, 'cars_test')
How to check if images are gray or rgb ?

ans : Now that you have the train and test directories, you can check the image type using the following code:

```
import os
import matplotlib.pyplot as plt
import numpy as np

Your paths
path = '/root/.cache/kagglehub/datasets/jessicali9530/stanford-cars-dataset/versions/2'
train_dir = os.path.join(path, 'cars_train')
test_dir = os.path.join(path, 'cars_test')

Get the first image from the train directory
img_path = os.path.join(train_dir, os.listdir(train_dir)[0])

Read the image
img = plt.imread(img_path)

Print the image shape
print(img.shape)
```

If the output is:

- `(height, width, 3)`, the images are RGB.
- `(height, width)`, the images are grayscale.

Run this code to check the image type!

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# example 1
data_gen = ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
)

model.fit(data_gen.flow(x_train, y_train, batch_size=64), epochs=15, validation_data=(x_test, y_test))

# example 2 for directory - example file - face recognition
dataset_dir = 'lfw_funneled' # directory path = lfw_funneled

datagen = ImageDataGenerator(rescale=1./255)

train_generator = datagen.flow_from_directory(
    dataset_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical'
)

history = model.fit(
    train_generator,
    epochs=10
)

In [ ]:
#basic structure of model for images
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(len(train_generator.class_indices), activation='softmax'))

# Compile model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


#-----------------or this model--------------------
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.1))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.1))

model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.1))

# model.add(Conv2D(256, (3, 3), activation='relu'))
# model.add(BatchNormalization())
# model.add(MaxPooling2D((2, 2)))
# model.add(Dropout(0.1))

model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.1))

model.add(Dense(10, activation='softmax'))

In [ ]:
# two ways to add batch size
history = model.fit(
    ds_train.batch(32),  # Batch size for training
    epochs=10,
    validation_data=ds_test.batch(32),  # Batch size for testing
)

#or this ---------
ds_train = ds_train.batch(32)
ds_test = ds_test.batch(32)

history = model.fit(
    ds_train,
    epochs=10,
    validation_data=ds_test,
)

# or this
data_gen = ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
)

model.fit(data_gen.flow(x_train, y_train, batch_size=64), epochs=15, validation_data=(x_test, y_test))

In [ ]:
# ------ for converting greyscale into rgb colors -----------

from PIL import Image
import numpy as np
x_train = np.array([Image.fromarray(img).resize((32, 32)) for img in x_train])
x_test = np.array([Image.fromarray(img).resize((32, 32)) for img in x_test])

# Repeat grayscale channel to create pseudo-RGB images
x_train = np.repeat(x_train[..., np.newaxis], 3, axis=3)
x_test = np.repeat(x_test[..., np.newaxis], 3, axis=3)

# Normalize pixel values
x_train = x_train.astype('float32') / 255
x_test = x_test.astype('float32') / 255

for converting greyscale into rgb colors

In [ ]:
# -----------------  it is a must for the images to reshape and normalize it -----------------

# Reshape and normalize images
x_train = x_train.reshape(-1, 28, 28, 1).astype('float32') / 255
x_test = x_test.reshape(-1, 28, 28, 1).astype('float32') / 255

it is a must for the images to reshape and normalize it

In [ ]:
# -----------------  python codefpr converting pixel values to images  -----------------

import numpy as np
from PIL import Image

# assuming 'pixels' is a string of space-separated pixel values
pixels = np.array(pixels.split(' ')).reshape(48, 48).astype('uint8')

# create an image from the pixel values
img = Image.fromarray(pixels)

# save the image to a file
img.save('image.png')

python code for converting pixel values to images

In [ ]:
!unzip -q /content/archive.zip -d /content/
-!ls /content/

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Define the paths to the train and test folders
train_path = '/content/train'
test_path = '/content/test'

# Define the data generators
train_datagen = ImageDataGenerator(
    rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)

test_datagen = ImageDataGenerator(rescale=1./255)

# Load training data
train_generator = train_datagen.flow_from_directory(
    train_path,
    target_size=(48, 48),
    batch_size=32,
    color_mode='grayscale',
    class_mode='categorical'
)

# Load testing data
test_generator = test_datagen.flow_from_directory(
    test_path,
    target_size=(48, 48),
    batch_size=32,
    color_mode='grayscale',
    class_mode='categorical'
)

whenever you have a zip file or tar file and you extract in in colab use above code -last example we have a zip file called - archive.zip , then it has folders test and train

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("jessicali9530/stanford-cars-dataset")

print("Path to dataset files:", path)

import kagglehub
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
import os

# Load dataset
train_dir = os.path.join(path, 'cars_train')
test_dir = os.path.join(path, 'cars_test')

# Load and preprocess data using Keras ImageDataGenerator
train_datagen = keras.preprocessing.image.ImageDataGenerator(rescale=1./255,
                                                                    shear_range=0.2,
                                                                    zoom_range=0.2,
                                                                    horizontal_flip=True)

test_datagen = keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(train_dir,
                                                        target_size=(224, 224),
                                                        batch_size=32,
                                                        class_mode='categorical')

test_generator = test_datagen.flow_from_directory(test_dir,
                                                      target_size=(224, 224),
                                                      batch_size=32,
                                                      class_mode='categorical')

buddy listen , whenever you download something from kaggle directly using code code - use this method

In [ ]:
------1. question - where to use sparse_categorical_crossentropy and categorical_crossentropy ?

ans - While it's technically working, it's still not the most correct or efficient approach.
Using sparse_categorical_crossentropy with one-hot encoded labels is a bit of a hack, relying on TensorFlow's internal conversion.

For clarity, maintainability, and performance, it's still recommended to:

- Use categorical_crossentropy with one-hot encoded labels.
- Use sparse_categorical_crossentropy with integer labels.

So, while it's working, I'd suggest switching to categorical_crossentropy for consistency and best practices.



----------2. question - "train_datagen = keras.preprocessing.image.ImageDataGenerator(rescale=1./255,
                                                                    shear_range=0.2,
                                                                    zoom_range=0.2,
                                                                    horizontal_flip=True)
test_datagen = keras.preprocessing.image.ImageDataGenerator(rescale=1./255)
train_generator = train_datagen.flow_from_directory(train_dir,
                                                        target_size=(224, 224),
                                                        batch_size=32,
                                                        class_mode='categorical')
test_generator = test_datagen.flow_from_directory(test_dir,
                                                      target_size=(224, 224),
                                                      batch_size=32,
                                                      class_mode='categorical') - which one is one hot encoding, how to check it" ?
ans - Run this code:
batch_images, batch_labels = next(train_generator)
print("Label shape:", batch_labels.shape)

2. Look at the output. It will show the shape of the labels.
3. If the shape has TWO numbers, like (32, 196), then the labels are ONE-HOT ENCODED.

Example output:
Label shape: (32, 196)

If you see TWO numbers, it means the labels are one-hot encoded!

---------following question: Two numbers (32,196)? Shouldn't it be 0 and 1?
ans- You're thinking of the actual values of the labels, but I was referring to the SHAPE of the labels.

In one-hot encoding:

- The shape has TWO numbers: (batch_size, num_classes)
- The values are indeed 0s and 1s, but the shape tells us it's one-hot encoded.

So:

- (32, 196) means 32 samples, each with 196 classes (one-hot encoded)
- The actual values would be 0s and 1s, like [0, 0, 1, 0, ...]

---------following question:What if it's not a one hot encoded data
Then how will it show
ans - If the data is NOT one-hot encoded:

- The shape will have ONLY ONE number: (batch_size,)
- The values will be integer labels (e.g., 0, 1, 2, ...)

Example:

- Shape: (32,)
- Values: [0, 1, 2, 0, 1, ...]

This indicates that the data is using integer labels, not one-hot encoding.

So, to summarize:

- One-hot encoded: (batch_size, num_classes) with 0s and 1s
- Integer labels: (batch_size,) with integer values

Imp example - Buddy!

Here's an example code:

```
import numpy as np

One-hot encoded labels
labels_one_hot = np.array([[0, 0, 1, 0],
                              [0, 1, 0, 0],
                              [1, 0, 0, 0]])

Print shape
print("Shape:", labels_one_hot.shape)

Print labels
print("Labels:")
print(labels_one_hot)
```

Output:

```
Shape: (3, 4)
Labels:
[[0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]
```

In this example:

- The shape is `(3, 4)`, which means there are 3 samples and 4 classes.
- The labels are one-hot encoded, with only one `1` per row.

Now, try this with your own labels, buddy!

------1. question - where to use sparse_categorical_crossentropy and categorical_crossentropy ?

ans - While it's technically working, it's still not the most correct or efficient approach.
Using sparse_categorical_crossentropy with one-hot encoded labels is a bit of a hack, relying on TensorFlow's internal conversion.

For clarity, maintainability, and performance, it's still recommended to:

- Use categorical_crossentropy with one-hot encoded labels.
- Use sparse_categorical_crossentropy with integer labels.

So, while it's working, I'd suggest switching to categorical_crossentropy for consistency and best practices.



----------2. question - "train_datagen = keras.preprocessing.image.ImageDataGenerator(rescale=1./255,
                                                                    shear_range=0.2,
                                                                    zoom_range=0.2,
                                                                    horizontal_flip=True)
test_datagen = keras.preprocessing.image.ImageDataGenerator(rescale=1./255)
train_generator = train_datagen.flow_from_directory(train_dir,
                                                        target_size=(224, 224),
                                                        batch_size=32,
                                                        class_mode='categorical')
test_generator = test_datagen.flow_from_directory(test_dir,
                                                      target_size=(224, 224),
                                                      batch_size=32,
                                                      class_mode='categorical') - which one is one hot encoding, how to check it" ?
ans - Run this code:
batch_images, batch_labels = next(train_generator)
print("Label shape:", batch_labels.shape)

2. Look at the output. It will show the shape of the labels.
3. If the shape has TWO numbers, like (32, 196), then the labels are ONE-HOT ENCODED.

Example output:
Label shape: (32, 196)

If you see TWO numbers, it means the labels are one-hot encoded!

---------following question: Two numbers (32,196)? Shouldn't it be 0 and 1?
ans- You're thinking of the actual values of the labels, but I was referring to the SHAPE of the labels.

In one-hot encoding:

- The shape has TWO numbers: (batch_size, num_classes)
- The values are indeed 0s and 1s, but the shape tells us it's one-hot encoded.

So:

- (32, 196) means 32 samples, each with 196 classes (one-hot encoded)
- The actual values would be 0s and 1s, like [0, 0, 1, 0, ...]

---------following question:What if it's not a one hot encoded data
Then how will it show
ans - If the data is NOT one-hot encoded:

- The shape will have ONLY ONE number: (batch_size,)
- The values will be integer labels (e.g., 0, 1, 2, ...)

Example:

- Shape: (32,)
- Values: [0, 1, 2, 0, 1, ...]

This indicates that the data is using integer labels, not one-hot encoding.

So, to summarize:

- One-hot encoded: (batch_size, num_classes) with 0s and 1s
- Integer labels: (batch_size,) with integer values

Imp example - Buddy!

Here's an example code:

```
import numpy as np

One-hot encoded labels
labels_one_hot = np.array([[0, 0, 1, 0],
                              [0, 1, 0, 0],
                              [1, 0, 0, 0]])

Print shape
print("Shape:", labels_one_hot.shape)

Print labels
print("Labels:")
print(labels_one_hot)
```

Output:

```
Shape: (3, 4)
Labels:
[[0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]
```

In this example:

- The shape is `(3, 4)`, which means there are 3 samples and 4 classes.
- The labels are one-hot encoded, with only one `1` per row.

Now, try this with your own labels, buddy!